using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface;
using Content.Client.Stylesheets;
using Robust.Client.Utility;
using Robust.Shared.Utility;
using Robust.Client.GameObjects;
using Content.Shared.PlayingCard;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.PlayingCard.UI
{
    [GenerateTypedNameReferences]
    public partial class PlayingCardHandWindow : DefaultWindow
    {
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly SpriteSystem _sprites = default!;
        // [Dependency] private readonly PlayingCardHandSystem _playingCardHandSystem = default!;

        private PlayingCardHandBoundUserInterface Owner { get; }

        private List<String> _cachedCardList = new();

        private int _cardOffset = 0;

        private int _cardPageLimit = 5;

        private const string PillsRsiPath = "/Textures/Objects/Fun/PlayingCards/nanotrasenbasiccards.rsi";

        private SpriteComponent? spriteComp;
        public PlayingCardHandWindow(PlayingCardHandBoundUserInterface owner, ClientUserInterfaceComponent component)
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Owner = owner;
            IoCManager.Resolve<IResourceCache>();

            ScrollRight.OnPressed += e => ChangeOffset(1);
            ScrollLeft.OnPressed += e => ChangeOffset(-1);

            spriteComp = IoCManager.Resolve<IEntityManager>().GetComponent<SpriteComponent>(component.Owner);
        }

        // private Control SupplyTooltip(Control? sender)
        public sealed class TestTooltip : PanelContainer
        {
            private const float TooltipTextMaxWidth = 128;
            public TestTooltip(string tooltipText)
            {
                SetOnlyStyleClass(StyleNano.StyleClassTransparentBorderedWindowPanel);

                BoxContainer vbox;
                AddChild(vbox = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    RectClipContent = true,
                    MaxWidth = TooltipTextMaxWidth,
                });

                var nameLabel = new RichTextLabel
                {
                    StyleClasses = {StyleNano.StyleClassTooltipActionDescription}
                };

                nameLabel.SetMessage(tooltipText);
                vbox.AddChild(nameLabel);
            }

        }

        private Control? SupplyTooltip(Control sender)
        {
            if (sender.ToolTip != null)
                return new TestTooltip(sender.ToolTip);

            return null;
        }

        public void Populate(List<String> cardList)
        {
            CardList.RemoveAllChildren();

            string playingCardContent = "NTPlayingCardContents";

            if (string.IsNullOrEmpty(playingCardContent))
                return;

            if (!_prototypeManager.TryIndex(playingCardContent, out PlayingCardContentsPrototype? playingCardContents))
                return;

            _cachedCardList = cardList;

            int start = Math.Max(0, ((cardList.Count - 1) - _cardOffset));
            int end = Math.Max(0, ((start + 1) - _cardPageLimit));



            // loop backwards because newest card is stacked onto the left
            for (int i = start; i >= end; i--) {

            var button = new CardButton
            {
                CardName = cardList[i],
                Index = i
            };
            button.IndexLabel.SetMessage((cardList.Count - i).ToString());
            button.ActualButton.ToolTip = cardList[i];
            button.ActualButton.TooltipDelay = 0.1f;
            button.ActualButton.TooltipSupplier = SupplyTooltip;

            // SET TEXTURES
            var rect = button.EntityTextureRects;

            if (playingCardContents.CardContents.TryGetValue(cardList[i], out string? cardLayerDetailsPrototypeID))
            {
                if (_prototypeManager.TryIndex(cardLayerDetailsPrototypeID, out PlayingCardDetailsPrototype? cardDetails))
                {
                    var resourcePath = new ResourcePath(PillsRsiPath);
                    var baseLayer = _sprites.Frame0(new SpriteSpecifier.Rsi(resourcePath, playingCardContents.BaseLayerState));
                    rect.Textures = new();
                    rect.Textures.Add((baseLayer, null));
                    if (cardDetails.LayerOneState != null)
                    {
                        var layerOneState = _sprites.Frame0(new SpriteSpecifier.Rsi(resourcePath, cardDetails.LayerOneState));
                        var layerOneColor = cardDetails.LayerOneColor;
                        rect.Textures.Add((layerOneState, layerOneColor));
                    }
                    if (cardDetails.LayerTwoState != null)
                    {
                        var layerTwoState = _sprites.Frame0(new SpriteSpecifier.Rsi(resourcePath, cardDetails.LayerTwoState));
                        var layerTwoColor = cardDetails.LayerTwoColor;
                        rect.Textures.Add((layerTwoState, layerTwoColor));
                    }
                }
            }

            // var rect = button.EntityTextureRects;
            // rect.Textures = SpriteComponent.GetPrototypeTextures(prototype, resourceCache).Select(o => o.Default).ToList();
                button.ActualButton.OnPressed += OnCardSelected;
                // button.CardNameLabel.SetMessage(cardList[i]);
                CardList.AddChild(button);
            }


        }

        private void ChangeOffset(float offsetChange)
        {
            if (!((_cachedCardList.Count - 1) < _cardPageLimit))
            {
                var newOffset = _cardOffset + offsetChange;
                if ((newOffset < 0) || (newOffset > _cachedCardList.Count - 1))
                    return;

                _cardOffset = (int)newOffset;
                Populate(_cachedCardList);
                return;
            }
            if (_cardOffset > 0)
                _cardOffset = 0;
        }

        protected override void MouseWheel(GUIMouseWheelEventArgs args)
        {
            base.MouseWheel(args);
            ChangeOffset(args.Delta.Y);
        }

        private void OnCardSelected(BaseButton.ButtonEventArgs args)
        {
            var item = (CardButton) args.Button.Parent!;
            Owner.RemoveCard(item.Index);
        }

        private sealed class CardButton : Control
        {
            public string CardName { get; set; } = default!;
            public Button ActualButton { get; private set; }
            public BoxContainer Box { get; private set; }
            public RichTextLabel IndexLabel { get; private set; }
            public LayeredColorTextureRect EntityTextureRects { get; private set; }
            // public SpriteView CardSpriteView { get; private set;}
            public int Index { get; set; }

            public CardButton()
            {
                AddChild(ActualButton = new Button
                {
                });

                AddChild(Box = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    MinSize = (64, 96),
                    MaxSize = (64, 96),
                    Children =
                    {
                        (IndexLabel = new RichTextLabel
                        {
                            MaxSize = (6, 6),
                            Margin = new Thickness(0, 0, 0, 0)
                        }),
                        (EntityTextureRects = new LayeredColorTextureRect
                        {
                            MinSize = (122, 122),
                            HorizontalExpand = true,
                            VerticalExpand = true,
                            HorizontalAlignment = HAlignment.Center,
                            VerticalAlignment = VAlignment.Center,
                            Stretch = TextureRect.StretchMode.KeepAspect,
                            Margin = new Thickness(0, 0, 0, 0)
                        }),
                    }
                });
            }
        }

        public class EntityContainerButton : ContainerButton
    {
        public string CardName;

        public EntityContainerButton(string cardName)
        {
            CardName = cardName;
            AddStyleClass(StyleNano.StyleClassStorageButton);
        }
    }
    }
}
